[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sae_tools"
version = "0.1.0"
description = "Analysis framework for SAE activations"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "torch>=2.6,<2.7",
    "transformer-lens>=3.1,<4",
    "sae-lens>=6.43,<7",
    "transformers>=4.57,<5",
    "huggingface-hub>=0.36",
    "hf-xet",
    "python-dotenv",
    "datasets",
    "pyyaml",
    "tqdm",
    "numpy",
    "pandas",
    "pyarrow",
    "scipy",
    "matplotlib",
    "seaborn",
    "ipywidgets"
]

[project.optional-dependencies]
dev = [
    "pytest"
]
workflow = [
    "snakemake>=8,<10"
]

[tool.setuptools.packages.find]
where = ["src"]
